pipelines: 

## Using NpmBuild step will fail due to issue https://jira.jfrog.org/browse/RTDEV-25641
  #     - name: npm_build_install
  #       type: NpmBuild
  #       configuration:
  #         resolverRepo: pe-npm
  #         sourceLocation: .
  #         integrations:
  #           - name: artifactory
  #         inputResources:
  #           - name: pe_source_code
   
  #     - name: npm_build_publish
  #       type: NpmPublish
  #       configuration:
  #         deployerRepo: pe-npm-local
  #         integrations:
  #           - name: artifactory
  #         inputSteps:
  #           - name: npm_build_install
  #         outputResources:
  #           - name: npm_app_build_info

  - name: npm_app_pipeline
    steps:    
      - name: bash_npm_build_publish
        type: Bash
        configuration: 
          environmentVariables: 
            buildName: bash_npm_build_publish
            buildNumber: "1.0.${run_number}"
          runtime:
            type: host
          integrations: 
            - name: artifactory
            - name: pegeneric
          inputResources:
            - name: pe_source_code
          outputResources: 
            - name: npm_app_build_info
        execution: 
          onExecute: 
            - printenv int_pegeneric_user
            - printenv int_pegeneric_password
            - printenv int_pegeneric_server
            - git clone https://github.com/davidpinhas/simple-reactjs-app.git
            - cd simple-reactjs-app
            - bash artifactory-config.sh
#            - if ! grep $int_pegeneric_server  ~/.jfrog/jfrog-cli.conf.v5; then jfrog config add $int_pegeneric_server --artifactory-url https://$int_pegeneric_server.jfrog.io/artifactory --user $int_pegeneric_user --password $int_pegeneric_password --interactive=false; fi
            - jfrog rt npm-config --server-id-resolve $int_pegeneric_server --server-id-deploy $int_pegeneric_server --repo-resolve pe-npm-remote --repo-deploy pe-npm-local
            - jfrog rt npmi --build-name=npm-app --build-number=1.0.${run_number}
            - jfrog rt bag npm-app 1.0.${run_number}
            - jfrog rt bce npm-app 1.0.${run_number}
            - jfrog rt bp npm-app 1.0.${run_number}
            - add_run_variables buildName=${JFROG_CLI_BUILD_NAME} buildNumber=${JFROG_CLI_BUILD_NUMBER}
            - add_run_variables myEnvironmentVariable=${run_id}
            - $jfrog_cli_path rt build-collect-env
            - add_run_files /tmp/jfrog/. jfrog

      - name: npm_publish_buildinfo
        type: PublishBuildInfo
        configuration:
          environmentVariables:
            buildStepName: bash_npm_build_publish
          inputSteps:
            - name: bash_npm_build_publish
          runtime:
            type: host
          outputResources:
            - name: npm_app_build_info

      - name: npm_app_scan
        type: XrayScan
        configuration:
          failOnScan: false
          inputSteps:
            - name: npm_publish_buildinfo
          inputResources:
            - name: npm_app_build_info

      - name: promoteNpmBuildStep
        type: PromoteBuild
        configuration:
          targetRepository: pe-prod-npm
          includeDependencies: true
          copy: true
          integrations:
            - name: artifactory
          inputResources:
            - name: npm_app_build_info
              trigger: true
          outputResources:
            - name: npm_app_build_info_propoted_prod
        execution:
          onSuccess:
            - write_output npm_app_build_info_propoted_prod version=${appVersion}
            - jfrog rt sp --build=${res_npm_app_build_info_buildName}/${res_npm_app_build_info_buildNumber} pe-npm-local/ "app.version=${appVersion}"

#Dockerized app
  - name: dockerized_npm_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
          dockerFrameworkVersion: ${res_docker_framework_build_info_promoted_version}
          dockerImageTagVersion: 1.0.${run_number}-${res_pe_source_code_commitSha}

    steps:
      - name: build_docker_npm_app
        type: DockerBuild
        configuration:
          affinityGroup: docker_group
          dockerFileName: Dockerfile
          dockerFileLocation: .
          dockerImageName: ${int_server_name_value}.jfrog.io/npm-app
          dockerImageTag: ${dockerImageTagVersion}
          dockerOptions: --build-arg SERVER_NAME=${int_server_name_value} --build-arg DOCKER_FRAMEWORK_VERSION=${dockerFrameworkVersion}
          inputResources:
            - name: pe_source_code
            - name: npm_app_build_info_propoted_prod
            - name: docker_framework_build_info_promoted
#            - name: npm_app_package
          integrations:
            - name: artifactory
            - name: docker
            - name: server_name
        execution:
          onStart:
            - add_pipeline_variables appVersion="${res_build_info_npm_app_promoted_staging_version}"
            - add_pipeline_variables triggerBuildInfoName="${res_build_info_npm_app_promoted_staging_buildName}"
            - add_pipeline_variables triggerBuildInfoNumber="${res_build_info_npm_app_promoted_staging_buildNumber}"
            - add_pipeline_variables myDockerTag="${dockerImageTagVersion}"

      - name: publish_docker_npm_app
        type: DockerPush
        configuration:
          affinityGroup: docker_group
          targetRepository: pe-docker-local
          autoPublishBuildInfo: true
          inputSteps:
            - name: build_docker_npm_app
          integrations:
            - name: artifactory
          outputResources:
            - name: docker_app_build_info

      - name: xray_scan_docker_build_info_npm_app
        type: XrayScan
        configuration:
          affinityGroup: docker_group
          failOnScan: true
          inputSteps:
            - name: publish_docker_npm_app
          inputResources:
            - name: docker_app_build_info

      - name: promoting_docker_build_info_app
        type: PromoteBuild
        configuration:
          affinityGroup: docker_group
          targetRepository: pe-docker-local
          includeDependencies: false
          status: "DOCKER_SCAN_OK"
          comment: "Xray scan passed succesfully"
          copy: "True"
          integrations:
            - name: artifactory
          inputResources:
            - name: docker_app_build_info
              trigger: true
          inputSteps:
            - name: xray_scan_docker_build_info_npm_app
          outputResources:
            - name: docker_app_build_info_promoted_prod
        execution:
          onSuccess:
            - write_output docker_app_build_info_promoted_prod "backimage=\"backapp\""
            - write_output docker_app_build_info_promoted_prod "backtag=${dockerImageTagVersion}"
            - jfrog rt sp --build=${res_docker_app_build_info_buildName}/${res_docker_app_build_info_buildNumber} pe-docker-local/**/manifest.json "docker.tag=${dockerImageTagVersion}"

      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          helmVersion: 3
          lint: true
          # affinityGroup: docker_group
          inputResources:
            - name: pe_source_code
          inputSteps:
            - name: promoting_docker_build_info_app
              trigger: true
          outputResources:
            - name: helm_chart_npm_app_resource
          chartPath: davidpinhas/simple-reactjs-app/chart
          flags: --app-version=${dockerImageTagVersion} --version 1.0.${run_number}
        execution:
          onStart:
            - CHART_VERSION=0.0.$run_number
            - pushd $res_app_gitrepo_resourcePath/chart
            - "sed -ie \"s/^version: .*$/version: $CHART_VERSION/\" Chart.yaml"
            - "sed -ie \"s/^appVersion: .*$/appVersion: $CHART_VERSION/\" Chart.yaml"
            - popd
