apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vfrog-npm-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - pe-task-demo.duckdns.org
    secretName: vfrog-tls-secret
  rules:
  - host: pe-task-demo.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vfrog-webapp-npm-app-chart
            port:
              number: 8080
